-- Подготовленная моделька
DROP TABLE IF EXISTS PreparedModel CASCADE;
CREATE TABLE PreparedModel
(
    id                  bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unpreparedModelId   bigint      NOT NULL UNIQUE,
    previewImage        text        NOT NULL,
    length              integer     NOT NULL,
    width               integer     NOT NULL,
    height              integer     NOT NULL,
    isHoled             boolean     NOT NULL,

    FOREIGN KEY (unpreparedModelId) REFERENCES UnpreparedModel(id)
);

-- Файл подготовленной модельки
DROP TABLE IF EXISTS PreparedModelFile CASCADE;
CREATE TABLE PreparedModelFile
(
    id                  bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    preparedModelId     bigint      NOT NULL,
    file                text        NOT NULL,
    fileformat          text        NOT NULL,

    FOREIGN KEY (preparedModelId) REFERENCES PreparedModel(id)
);