-- Подготовленная моделька
DROP TABLE IF EXISTS prepared_models CASCADE;
CREATE TABLE prepared_models
(
    id                      bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unprepared_model_id     bigint      NOT NULL UNIQUE,
    preview_image           text        NOT NULL,
    is_holed                boolean     NOT NULL,
    length                  integer     NOT NULL,
    width                   integer     NOT NULL,
    height                  integer     NOT NULL,
    file_model              text        NOT NULL,

    UNIQUE (unprepared_model_id, is_holed),
    FOREIGN KEY (unprepared_model_id) REFERENCES unprepared_models (id) ON DELETE CASCADE
);

-- Файл подготовленной модельки
DROP TABLE IF EXISTS prepared_model_files CASCADE;
CREATE TABLE prepared_model_files
(
    id                  bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prepared_model_id   bigint      NOT NULL,
    file_format         text        NOT NULL,
    file                text        NOT NULL,

    FOREIGN KEY (prepared_model_id) REFERENCES prepared_models (id) ON DELETE CASCADE
);